### ISSUE TITLE
Errors when installing

### ISSUE THREAD

**Issue by shelikescoding** [NehemiahK/Another-React-Lib#100]
Hi @NehemiahK , 
I followed your step and clone the repo. It looks good.
Unfortunately, I got some errors when trying to npm star. Here's the log: 
`Failed to compile with 3 errors.

 ERROR  in ./demo/src/index.js 94:26-34
"export 'Collapse' was not found in '../../src/index'
 @ multi ./node_modules/nwb/polyfills.js (webpack)-dev-server/client?/ (webpack)/hot/only-dev-server.js ./demo/src/index.js

 ERROR  in ./demo/src/index.js 135:26-33
"export 'Profile' was not found in '../../src/index'
 @ multi ./node_modules/nwb/polyfills.js (webpack)-dev-server/client?/ (webpack)/hot/only-dev-server.js ./demo/src/index.js

 ERROR  in ./demo/src/index.js 159:26-35
"export 'Searchbar' was not found in '../../src/index'
 @ multi ./node_modules/nwb/polyfills.js (webpack)-dev-server/client?/ (webpack)/hot/only-dev-server.js ./demo/src/index.js
`

Thanks for your contribution to Hacktoberfest ! :smile:

**Comment by abdelelamel** [comment]
i think #99 will fix your issues

**Comment by NehemiahK** [comment]
Also #103 will hopefully address this concern
