### ISSUE TITLE
Automated Checks

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#103]
It's getting hard to manage the demo file and the index file. I will update these files periodically.

Does anyone know how to add in automated checks to make sure they won't be able to merge if these files were touched?

**Comment by NehemiahK** [comment]
Also if anyone can't take the issue, but has an idea, that's great too!

**Comment by ntieman** [comment]
I have an idea. I'm working on a branch now.

**Comment by ntieman** [comment]
Just to clarify, you want the merge to abort if anyone but you modifies these two files?

**Comment by NehemiahK** [comment]
As in they wont be able to make the pull request. Is that doable? I've seen other repositories with a check and won't allow you to make the pull request if it doesn't meet certain criteria

**Comment by ntieman** [comment]
That was a little different than I was thinking, but I'll see if I can chase it down. Can you remember a repository that does this that I could look at?

**Comment by NehemiahK** [comment]
@ntieman check this project out: https://github.com/NehemiahK/jsonmc

**Comment by ntieman** [comment]
I'm not seeing the checks in the repository itself, so I'm guessing they're using the Github hooks. It looks like you could accomplish what you're talking about with a CI server and a custom status. Unfortunately, you have to build/buy your own CI hosting, which I have no experience with. I don't think I'll be able to get this done.

- [Enbabling Required Status Checks](https://help.github.com/en/articles/enabling-required-status-checks)
- [Building a CI Server](https://developer.github.com/v3/guides/building-a-ci-server/)

Originally I was thinking of using something in the repo itself, like a Husky pre-commit check. Those can be arbitrary scripts, so I think you could check for specific files modified, and check which user is merging, but these checks can be bypassed. 

- [Husky](https://www.npmjs.com/package/husky)

**Comment by NehemiahK** [comment]
Ah okay thanks. Maybe i'll take a look into that. I'll close this issue for now

**Comment by NehemiahK** [comment]
Must have been from nwb
