### ISSUE TITLE
Beating Heart Component

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#129]
Would be cool if we had a component then when hovered on starts to beat. Should be able to pick size of sm,md,lg. and maybe 2 - 3 colors with default being red

**Comment by AnnaelleS** [comment]
Would like to try that if possible !
You'd like the user to be able to choose between 3 sizes and ~3 colors and it would change the heart depending on that ? :)

**Comment by NehemiahK** [comment]
As in it can be passed in as props in React. In the browser when hovering it will beat

**Comment by AnnaelleS** [comment]
Alright! I'm absolutely new to React but that's a pretty good challenge :) 

Thanks, will do my best

**Comment by NehemiahK** [comment]
Awesome, i generally find the css to be hard. = )

**Comment by Karan710** [comment]
Can i work on it?

**Comment by NehemiahK** [comment]
@Karan710 i think @AnnaelleS is working on it

**Comment by AnnaelleS** [comment]
I am working on it indeed. Sorry, takes a little bit more time than planned. Should be finished by tomorrow EOD.

**Comment by AnnaelleS** [comment]
Done #169 :)
