### ISSUE TITLE
Component Styling - CSS (General Issue)

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#134]
Would be great if people could take a look at some of the existing components and then open issues with some of the components that could be improved.

**Comment by willcezar00** [comment]
I Think  that will be a a good idea to create a sidebar menu and organize the index.js home page with componets separeted in categories.

**Comment by NehemiahK** [comment]
That is a good idea! Want to open up an issue for that @willcezar00

**Comment by willcezar00** [comment]
Yes, I'll open a issue for that, sorry for the delay.
