### ISSUE TITLE
Css Files Leaking 

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#146]
It seems like the css files are going one on the other. The Button component is being overwritten by other styles

**Comment by BarnikRay** [comment]
I want to work on this issue

**Comment by NehemiahK** [comment]
Okay I found the issue. As far as I understand people just need to use unique css names for their component and that will fix the issue. Would you like to update the documentation? (CSS names need to be unique for the component and not take names like "blue,red" etc..

**Comment by BarnikRay** [comment]
Yeah I saw the same.. which doc shall I update?

**Comment by NehemiahK** [comment]
The contributing doc please, along the places where it says not to touch the index files =) thank you

**Comment by BarnikRay** [comment]
Thanks will do the same
