### ISSUE TITLE
Organize components by category

### ISSUE THREAD

**Issue by willcezar00** [NehemiahK/Another-React-Lib#151]
The **index.js** file is getting full os components with no organization

The Idea is to create a sidebar with some menus, like
 Input, Buttton, Misc. To keep the front page organized and easy to indentify what has been done.

**Comment by karan171996** [comment]
Can I Put these components in organized form ??

**Comment by NehemiahK** [comment]
Any ideas for this implementation? Because I just removed the components from the index file, so it isn't messy at this point. @willcezar00

**Comment by willcezar00** [comment]
Yeah, I Just saw this, but I'm still thing that can have a first page that works like a show case, but to avoid the conflicts that was happening, only one person mantain this, instead to everyone puts news components there.
here is a example : http://primefaces.org/primeng/

**Comment by NehemiahK** [comment]
Alright, i'm hoping no one will be touching the file at this point and I will update the index periodically
