### ISSUE TITLE
Styled List Component 

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#17]
Li's are nice, but they don't look great. It would be nice if you could just have a <List /> that would take an array as a property and generate a nice looking list.

**Comment by dishankmehta** [comment]
I would love to help on this one!

**Comment by NehemiahK** [comment]
Awesome, will assign to you.

**Comment by NehemiahK** [comment]
@dishankmehta still in progress?

**Comment by dishankmehta** [comment]
Yes. Give me some time. I will work on it this weekend if you don't mind.

**Comment by NehemiahK** [comment]
Of course. Just checking people didn’t forget since so many are eager to get involved :)

**Comment by dishankmehta** [comment]
Hey, created the pull request for the List component
