### ISSUE TITLE
Avatar Component

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#18]
It's common to have an avatar in different places on your site, it would be nice to just pass in a src and what type of Avatar Component it should be, circular, square, and maybe small or medium sized.

**Comment by hallowcard13** [comment]
hi @NehemiahK , can i work on this ?

**Comment by NehemiahK** [comment]
Of course! Assigning to you

**Comment by hallowcard13** [comment]
waiting for this PR to be merge before i will start working adding the feature #20

**Comment by edgarberlinck** [comment]
Nice. There is some work to put on this. Maybe a default icon if none is provided. 
> waiting for this PR #20 to be merge before i will start working adding the feature

**Comment by hallowcard13** [comment]
@NehemiahK  why you have closed it ? does this mean i will not continue working on this ?
