### ISSUE TITLE
Social Icons

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#21]
Would be nice to have a social icon for Github, Twitter, and LinkedIn, then all you need to pass in is your href and the size (small, medium, large)

**Comment by raghubandaru** [comment]
Shall I start coding this?

**Comment by NehemiahK** [comment]
That would be great!

**Comment by raghubandaru** [comment]
Should I continue working on this?

**Comment by NehemiahK** [comment]
Yeah, it would be nice actually if the social components would be wrapped inside of a link and could be passed a link

**Comment by raghubandaru** [comment]
I added Facebook, Github and Twitter from FontAwesome icons and working on my own version. Should I continue with it or work on the version you merged from edgarberlinck? I am a bit confused there!

**Comment by NehemiahK** [comment]
sorry, i just saw this. i need to see if i opened an issue
