### ISSUE TITLE
Navbar Component 

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#3]
Add a navbar component. I'll leave the implementation details up to you =).

**Comment by mkamranhamid** [comment]
Do you have any style in mind or anything?

**Comment by NehemiahK** [comment]
Hey, whatever you think looks nice. But I figured it would be nice to maybe have the option between a light theme and a dark theme. Use your imagination =) Happy to give more guidance though

**Comment by mkamranhamid** [comment]
Please assign it to me

**Comment by NehemiahK** [comment]
Assigned.

**Comment by mkamranhamid** [comment]
Added a PR [#150](https://github.com/NehemiahK/Another-React-Lib/pull/150) can you please close this
