### ISSUE TITLE
Footer Component 

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#33]
The footer should be styled nicely and have 1 or 2 themes, and as children it would display whatever the user wants to put in the footer

**Comment by iamawaisakram** [comment]
I would like to work on this as well! :-)

**Comment by NehemiahK** [comment]
all yours

**Comment by moficodes** [comment]
I did not see @iamawaisakram as assignee and ended up working on it 😔

**Comment by moficodes** [comment]
I did not see @iamawaisakram as assignee and ended up working on it 😔

#82

**Comment by NehemiahK** [comment]
@iamawaisakram is this being worked on?

**Comment by iamawaisakram** [comment]
@NehemiahK Yeah, I had 4 issues opened, submitted the other three, I came to submit this one and noted that PR was already submitted!

**Comment by iamawaisakram** [comment]
#164
