### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#34]
A way to make your text display nicely. 

Check out [bootstrap's card ](https://getbootstrap.com/docs/4.3/components/card/)

**Comment by iamawaisakram** [comment]
I would like to work on this as well! 😄

**Comment by NehemiahK** [comment]
wow! alright, i'll have to come up with some more issues then =)

**Comment by iamawaisakram** [comment]
#153 Created Pull request!

![image](https://user-images.githubusercontent.com/36075652/66271178-79462000-e874-11e9-9c23-26f948691951.png)
