### ISSUE TITLE
Card Loading Skeleton

### ISSUE THREAD

**Issue by iamawaisakram** [NehemiahK/Another-React-Lib#37]
So, It will be made generic, but I'll first create it for the card component and then will try to transition it to generic shapes like table, rows, header etc. Is that Okay?

**Comment by NehemiahK** [comment]
Can you explain what you mean?

**Comment by iamawaisakram** [comment]
Check this out! 
https://www.npmjs.com/package/react-loading-skeleton

**Comment by NehemiahK** [comment]
Looks interesting. go for it

**Comment by iamawaisakram** [comment]
#155 Pull Request Created!

![image](https://user-images.githubusercontent.com/36075652/66271673-4ef76100-e87a-11e9-81f1-fd5cfbd86aee.png)
