### ISSUE TITLE
Styled Select Dropdown

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#47]
A styled select dropdown with options passed in as an array. probably should take an onChange event.

**Comment by nik72619c** [comment]
working on this one. please assign me on this

**Comment by NehemiahK** [comment]
Sure thing!

**Comment by nik72619c** [comment]
Can I use an npm module for it or should I use the <select> ?

**Comment by NehemiahK** [comment]
Better to use select

**Comment by nik72619c** [comment]
#136
