### ISSUE TITLE
Profile Component 

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#48]
The component could take an image, text, and a description. Think about it like a tinder profile. Use your imagination =)

**Comment by Joshua-Burleson** [comment]
If this is available I'd like to take it.

**Comment by NehemiahK** [comment]
go for it

**Comment by karan171996** [comment]
If it is still not done, i will love to contribute to it.

**Comment by Joshua-Burleson** [comment]
> If it is still not done, i will love to contribute to it.

the initial component has been completed but #122 is up for grabs for styling options
