### ISSUE TITLE
Improve Header Component 

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#61]
Currently the elements in the header component are hardcoded, that should be fixed. 
Also it doesn't take up the full width. 
It would also be cool if it had a hamburger menu for responsive awesomeness

**Comment by brunodhr** [comment]
I will be happy to take a look at this!

**Comment by NehemiahK** [comment]
Excellent!

**Comment by NehemiahK** [comment]
closed
