### ISSUE TITLE
Style Guide or Formatter?

### ISSUE THREAD

**Issue by jamessral** [NehemiahK/Another-React-Lib#66]
Since Hacktobefest is here (it's what brought me here), should there be either a Style Guide and a Linter and/or a Formatter?

If so, I would be more than willing to add it. I have no preference one way or the other for which style/tool, but it could be nice to have one.

A potential suggestion would be just stock Eslint + stock Prettier

**Comment by NehemiahK** [comment]
That sounds cool, i'm not so familiar with those. What would it entail exactly?

**Comment by NehemiahK** [comment]
Also, what would this mean for already submitted and merged code?

**Comment by jamessral** [comment]
The linter just points out potential errors and/or stylistic concerns. The formatter just takes your code and puts it into a consistent format. It helps eliminate bike shedding on semi-colons vs. no semi-colons, double vs. single quotes, etc. It keeps the code looking more unified style wise. There are plugins for all of the major editors for these, so they will show errors and can often format on save (so that you don't even have to think about it).

A style guide can also go beyond this such as specifying class components vs. functional, arrow functions vs `function` keyword, etc. That is perhaps something better for down the road, but maybe not useful at this point.

**Comment by jamessral** [comment]
If it's something you'd like, I can format previous code and fix any errors that arise.

**Comment by jamessral** [comment]
If put together, Eslint covers potential errors, and Prettier does the formatting for you.

**Comment by NehemiahK** [comment]
Sounds like a great idea, good initiative!

**Comment by jamessral** [comment]
I'll make a PR
